import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Phone } from "lucide-react";
import { businessConfig, phoneHref, whatsappHref } from "../../../config/business";
import { eventImages, services } from "../../../content/site";
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=services.find(x=>x.slug===slug);return s?{title:s.title,description:`${s.shortDescription} Explore customized ${s.title.toLowerCase()} in Indore with Celebrate Life.`}:{}}
export default async function Service({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const wa=whatsappHref(`Selected service: ${s.title}`);const visual=eventImages[(Number(s.id)-1)%eventImages.length];return <><section className="service-detail-hero"><div><p className="eyebrow">{s.category} · Indore</p><h1>{s.title}</h1><p>{s.fullDescription}</p><div className="feature-chips">{s.features.map(f=><span key={f}>{f}</span>)}</div><div className="hero-actions"><Link className="button" href={`/book?service=${s.slug}`}>Book this service <ArrowRight/></Link><a className="text-link" href={phoneHref(businessConfig.primaryPhone)}><Phone/> Call</a></div></div><figure><Image src={visual.src} alt={`${s.title} decoration inspiration`} fill sizes="50vw"/></figure></section><section className="page-content"><div className="prose-grid"><div><p className="eyebrow dark">Made around your moment</p><h2>What we can<br/><em>shape together.</em></h2></div><div><h3>Best for</h3><p>Celebrations where a focused visual setting, personalised colour direction and photo-ready focal point are important.</p><h3>Possible elements</h3><p>Backdrop styling, balloon arrangements, personalised signs, lighting accents, cake-table details, floral elements and props can be discussed. Your quotation will confirm actual inclusions.</p><h3>How customisation works</h3><p>Share the venue, date, event type, preferred colours and inspiration. The team will discuss what is achievable before confirming the concept.</p>{wa&&<a className="button button-dark" href={wa} target="_blank" rel="noopener noreferrer">Enquire on WhatsApp</a>}</div></div></section></>}
